version: 1.0.{build}

image: Visual Studio 2017

environment:  
  DOCKER_USER:
    secure: i9T30C3Gi5+mGazI8PaXEA==
  DOCKER_PASS:
    secure: cIvXg8+kCw2JDjLaXUoKx/jAGsuIvnd6JeLDMcts7K8=
  SLACK_TOKEN:
    secure: +gRgRLkDDz+KHCNR+2HPcuTnobBNinqAxDbSfyd3kLuGc+qZXJmfCzes8YtFAa0L
  ADMIN_USER_ID:
    secure: pwPxIeKym+oeY9BQe/c+oA==
install:  
  - docker version

configuration:
 - Release

matrix:
  fast_finish: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore

build:
  project: Hjerpbakk.Profilebot.sln
  verbosity: minimal

test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"Test.Hjerpbakk.Profilebot\bin\Debug\Test.Hjerpbakk.Profilebot.dll -noshadow" -output:"coverage.xml" -filter:"+[Hjerpbakk.*]* -[Test.Hjerpbakk*]*"
after_test:
 - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - codecov -f "coverage.xml"
 
deploy_script:  
 - Set-Content -Path Hjerpbakk.Profilebot.Runner\bin\Release\Configuration\config.json -Value (Get-Content Hjerpbakk.Profilebot.Runner\bin\Release\Configuration\config.default.json).replace('[apiToken]', '$env:SLACK_TOKEN')
 - Set-Content -Path Hjerpbakk.Profilebot.Runner\bin\Release\Configuration\config.json -Value (Get-Content Hjerpbakk.Profilebot.Runner\bin\Release\Configuration\config.default.json).replace('[adminUserId]', '$env:ADMIN_USER_ID')
 - docker build -t hjerpbakk/profilebot .
 - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
 - docker push me/myfavoriteapp
